from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0754bea00d89'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('url_linkedin', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('url_sito', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('nazione', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('citta', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('settore', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('tipo_azienda', sa.Enum('STARTUP', 'PMI',
                                                      'CORPORATE', name='enumtipoazienda'), nullable=False),
                    sa.Column('cta_email', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('task',
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('company_info_id', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['company_info_id'], [
                                            'company_info.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('company_info')
    op.execute("DROP TYPE enumtipoazienda")
    # ### end Alembic commands ###
