"""empty message

Revision ID: ba33fe6acf87
Revises: f4a8b5c9d2e1
Create Date: 2025-10-30 19:08:41.950144

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ba33fe6acf87'
down_revision = 'f4a8b5c9d2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    taskstatusenum = sa.Enum('pending', 'running', 'completed', 'failed', name='taskstatusenum')
    taskstatusenum.create(op.get_bind(), checkfirst=True)

    # Then alter the column to use the enum type
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=taskstatusenum,
               existing_nullable=False,
               postgresql_using='status::taskstatusenum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, alter the column back to VARCHAR
    op.alter_column('task', 'status',
               existing_type=sa.Enum('pending', 'running', 'completed', 'failed', name='taskstatusenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using='status::text')

    # Then drop the enum type
    taskstatusenum = sa.Enum('pending', 'running', 'completed', 'failed', name='taskstatusenum')
    taskstatusenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
